module.exports = {
    apps: [
    {
      name: "StargateS0",
      script: "stargateSharded.php",
      args: "0 6",
      max_memory_restart: '4000M', 
      interpreter: 'php',
      cwd: "./",
      watch: false,
      watch_delay: 1000,
      ignore_watch : ["vendor"],
    },
    {
      name: "StargateS1",
      script: "stargateSharded.php",
      args: "1 6",
      max_memory_restart: '4000M', 
      interpreter: 'php',
      cwd: "./",
      watch: false,
      watch_delay: 1000,
      ignore_watch : ["vendor"],
    },
    {
      name: "StargateS2",
      script: "stargateSharded.php",
      args: "2 6",
      max_memory_restart: '4000M', 
      interpreter: 'php',
      cwd: "./",
      watch: false,
      watch_delay: 1000,
      ignore_watch : ["vendor"],
    },
    {
      name: "StargateS3",
      script: "stargateSharded.php",
      args: "3 6",
      max_memory_restart: '4000M', 
      interpreter: 'php',
      cwd: "./",
      watch: false,
      watch_delay: 1000,
      ignore_watch : ["vendor"],
    },
    {
      name: "StargateS4",
      script: "stargateSharded.php",
      args: "4 6",
      max_memory_restart: '4000M', 
      interpreter: 'php',
      cwd: "./",
      watch: false,
      watch_delay: 1000,
      ignore_watch : ["vendor"],
    },
    {
      name: "StargateS5",
      script: "stargateSharded.php",
      args: "5 6",
      max_memory_restart: '4000M', 
      interpreter: 'php',
      cwd: "./",
      watch: false,
      watch_delay: 1000,
      ignore_watch : ["vendor"],
    },

  ]}